version: '3.5'

services:

  ravendb:
    container_name: marketplace-ch9-ravendb
    image: ravendb/ravendb
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"

  # postgres:
  #   container_name: marketplace-ch9-postgres
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
